form/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('form_index/', views.form_index, name='form_index'),
    path('crear/', views.crear_formulario, name='crear_formulario'),
    path('listar/', views.listar_formularios, name='listar_formularios'),
    path('detalle/<int:formulario_id>/', views.detalle_formulario, name='detalle_formulario'),  # Nueva ruta para ver detalles

]

myproject/urls.py

from django.contrib import admin
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect



urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('home/', include('home.urls')), 
    path('formularios/', include('formularios.urls')),
    path('accounts/', include('accounts.urls')),
    path('form/', include('form.urls')),
    path('asignaciones/', include('asignaciones.urls')),
    path('respuestas/', include('respuestas.urls')),
    path('feedback/', include('feedback.urls')),
    path('', lambda _: redirect('accounts/logout')),  # Redirige a la ruta 'logout' sin namespace
]

form/models.py
from django.db import models

class Formulario(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Pregunta(models.Model):
    TIPO_RESPUESTA = [
        ('abierta', 'Abierta'),
        ('cerrada', 'Sí/No'),
    ]
    
    grupo = models.ForeignKey(Formulario, related_name='preguntas', on_delete=models.CASCADE)
    texto = models.CharField(max_length=500)
    tipo_respuesta = models.CharField(max_length=8, choices=TIPO_RESPUESTA)

    def __str__(self):
        return self.texto

form/forms.py
from django import forms
from .models import Formulario, Pregunta

class FormularioForm(forms.ModelForm):
    class Meta:
        model = Formulario
        fields = ['nombre', 'descripcion']

class PreguntaForm(forms.ModelForm):
    class Meta:
        model = Pregunta
        fields = ['texto', 'tipo_respuesta']

form/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FormularioForm, PreguntaForm
from .models import Formulario, Pregunta  # Importar el modelo

def form_index(request):
    # Recuperar todos los formularios
    formularios = Formulario.objects.all()
    return render(request, 'form/form_index.html', {'formularios': formularios})

def crear_formulario(request):
   # Crear un formulario con nombre y descripción
    if request.method == 'POST':
        if 'nombre' in request.POST and 'descripcion' in request.POST:
            # Crear el formulario (con nombre y descripción)
            formulario = Formulario(
                nombre=request.POST['nombre'],
                descripcion=request.POST['descripcion']
            )
            formulario.save()  # Guardar el formulario

            # Redirigir a la misma vista para agregar preguntas
            return redirect('crear_formulario')  # Recargar la página

        elif 'grupo_formulario' in request.POST and 'pregunta' in request.POST:
            # Agregar preguntas al formulario seleccionado
            grupo_formulario = Formulario.objects.get(id=request.POST['grupo_formulario'])
            pregunta_texto = request.POST['pregunta']
            tipo_respuesta = request.POST['tipo_respuesta']

            pregunta = Pregunta(
                texto=pregunta_texto,
                grupo=grupo_formulario,
                tipo_respuesta=tipo_respuesta
            )
            pregunta.save()  # Guardar la pregunta

            # Redirigir a la misma vista para seguir agregando preguntas
            return redirect('crear_formulario')  # Recargar la página

    # Recuperar todos los formularios creados para seleccionar uno
    formularios = Formulario.objects.all()

    # Filtrar las preguntas por el formulario seleccionado, si existe un formulario seleccionado
    formulario_id = request.GET.get('grupo_formulario', None)
    if formulario_id:
        preguntas = Pregunta.objects.filter(grupo_id=formulario_id)
    else:
        preguntas = Pregunta.objects.all()

    return render(request, 'form/crear_formulario.html', {'formularios': formularios,
        'preguntas': preguntas})



def listar_formularios(request):
    formularios = Formulario.objects.all()  # Obtener todos los formularios
    return render(request, 'form/listar_formularios.html', {'formularios': formularios})

def detalle_formulario(request, formulario_id):
    formulario = get_object_or_404(Formulario, id=formulario_id)
    return render(request, 'form/detalle_formulario.html', {'formulario': formulario})

form/templates/form/crear_formulario.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="./../../static/css/styles.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            {% include 'Componentes/navbar_admin.html' %}
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                {% include 'Componentes/sidebar_admin.html' %}
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Creacion de Formulario</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Crear tus grupos de preguntas</li>
                        </ol>

                        <!-- Crear formulario -->
                        <form method="POST">
                            {% csrf_token %}

                            <div class="mb-3">
                                <label for="nombre" class="form-label">Nombre del Formulario</label>
                                <input class="form-control" id="nombre" name="nombre" required>
                            </div>

                            <div class="mb-3">
                                <label for="descripcion" class="form-label">Descripción</label>
                                <textarea class="form-control" id="descripcion" name="descripcion" required></textarea>
                            </div>

                            <div class="d-flex">
                                <button type="submit" class="btn btn-primary ms-auto m-3">Crear Formulario</button>
                            </div>
                        </form>

                        <hr>
                        <h3>Agregar tus preguntas al formulario:</h3>
                        <!-- Agregar preguntas -->
                        <form method="POST">
                            {% csrf_token %}

                            <!-- Selección del formulario para agregar preguntas -->
                            <div class="mb-3">
                                <label for="grupo_formulario" class="form-label">Seleccione el Formulario</label>
                                <select name="grupo_formulario" class="form-control" required>
                                    {% for formulario in formularios %}
                                        <option value="{{ formulario.id }}">{{ formulario.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <!-- Campo para ingresar la pregunta -->
                            <div class="mb-3">
                                <label for="pregunta" class="form-label">Pregunta</label>
                                <input type="text" class="form-control" id="pregunta" name="pregunta" required placeholder="Escribe la pregunta">
                            </div>

                            <!-- Tipo de respuesta -->
                            <div class="mb-3">
                                <label for="tipo_respuesta" class="form-label">Tipo de Respuesta</label>
                                <select name="tipo_respuesta" class="form-control" required>
                                    <option value="abierta">Abierta</option>
                                    <option value="cerrada">Sí/No</option>
                                </select>
                            </div>

                            <div class="d-flex">
                                <button type="submit" class="btn btn-primary ms-auto m-3">Agregar Pregunta</button>
                            </div>
                        </form>

                        <hr>

                        <!-- Tabla de preguntas relacionadas con el formulario seleccionado -->
                        <h3>Preguntas del Formulario:</h3>

                        <!-- Selección de formulario para filtrar preguntas -->
                        <form method="GET">
                            <div class="mb-3">
                                <label for="grupo_formulario" class="form-label">Filtrar Preguntas por Formulario</label>
                                <select name="grupo_formulario" class="form-control" onchange="this.form.submit()">
                                    <option value="">Seleccione un formulario</option>
                                    {% for formulario in formularios %}
                                        <option value="{{ formulario.id }}" {% if formulario.id == request.GET.grupo_formulario %}selected{% endif %}>{{ formulario.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </form>
                        <div class="mb-3">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Pregunta</th>
                                        <th scope="col">Tipo de Respuesta</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for pregunta in preguntas %}
                                        <tr>
                                            <td>{{ pregunta.texto }}</td>
                                            <td>{{ pregunta.get_tipo_respuesta_display }}</td>  <!-- Muestra la descripción del tipo de respuesta -->
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            <td colspan="2">No hay preguntas asociadas a este formulario.</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>


                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; SkillScope 2024</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="./../../static/js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="./../../static/assets/demo/chart-area-demo.js"></script>
        <script src="./../../static/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="./../../static/js/datatables-simple-demo.js"></script>

        <script>
            document.getElementById('agregarPregunta').addEventListener('click', function () {
                var inputPregunta = document.querySelector('input[name="pregunta"]');
                var preguntaTexto = inputPregunta.value;
                var selectTipoRespuesta = document.querySelector('select[name="tipo_respuesta"]');
                var tipoRespuesta = selectTipoRespuesta.value;

                // Verifica que la pregunta no esté vacía
                if (preguntaTexto.trim() !== '') {
                    var tabla = document.getElementById('tablaPreguntas').getElementsByTagName('tbody')[0];

                    // Crear una nueva fila para la pregunta y tipo de respuesta
                    var nuevaFila = document.createElement('tr');

                    // Crear una celda para la pregunta
                    var celdaPregunta = document.createElement('td');
                    celdaPregunta.textContent = preguntaTexto;
                    nuevaFila.appendChild(celdaPregunta);

                    // Crear una celda para el tipo de respuesta
                    var celdaTipoRespuesta = document.createElement('td');
                    celdaTipoRespuesta.textContent = tipoRespuesta === 'abierta' ? 'Abierta' : 'Sí/No';
                    nuevaFila.appendChild(celdaTipoRespuesta);

                    // Añadir la fila a la tabla
                    tabla.appendChild(nuevaFila);

                    // Limpiar el campo de la última pregunta ingresada
                    inputPregunta.value = '';
                    selectTipoRespuesta.value = 'abierta';  // Resetear tipo de respuesta
                }
            });
        </script>
    </body>
</html>

form/templates/form/detalle_formulario.html
<!-- templates/form/detalle_formulario.html -->
{% extends 'listar_formularios.html' %}

{% block content %}
  <h1>{{ formulario.nombre }}</h1>
  <p>{{ formulario.descripcion }}</p>
  <!-- Agrega otros detalles del formulario aquí -->
  
  <a href="{% url 'form_index' %}">Volver al listado</a>
{% endblock %}

form/templates/form/form_index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="./../../static/css/styles.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            {% include 'Componentes/navbar_admin.html' %}
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                {% include 'Componentes/sidebar_admin.html' %}
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Creacion de Formulario </h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Crear tus grupos de preguntas</li>
                        </ol>
                        
                        <a href="{% url 'crear_formulario' %}" class="btn btn-primary ms-auto m-3">Crear nuevo formulario</a>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Descripción</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for formulario in formularios %}
                                    <tr>
                                        <td>{{ formulario.nombre }}</td>
                                        <td>{{ formulario.descripcion }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="3">No se han creado formularios aún.</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% block content %}  <!-- Este bloque se llena en las plantillas hijas -->
                        {% endblock %}
                    </div>
                    
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; SkillScope 2024</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="./../../static/js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="./../../static/assets/demo/chart-area-demo.js"></script>
        <script src="./../../static/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="./../../static/js/datatables-simple-demo.js"></script>
    </body>
</html>

form/templates/form/listar_formularios.html
<!-- templates/form/listar_formularios.html -->
{% extends 'form_index.html' %}

{% block content %}
<table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Acción</th>
      </tr>
    </thead>
    <tbody>
      {% for formulario in formularios %}
        <tr>
          <td>{{ forloop.counter }}</td>  <!-- Muestra el número de índice del formulario -->
          <td>{{ formulario.nombre }}</td>
          <td>
            <a href="{% url 'detalle_formulario' formulario.id %}" class="btn btn-info btn-sm">Ver detalles</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No se han creado formularios aún.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}